services:
  admin:
    build: 
      context: .
      dockerfile: admin/Dockerfile
    volumes:
      - ./shared/app.db:/usr/src/app/app.db
      - ./shared/notes/:/usr/src/app/notes
    environment:
      - TZ=Europe/Prague
  public:
    build: 
      context: .
      dockerfile: public/Dockerfile
    volumes:
      - ./shared/app.db:/usr/src/app/app.db
      - ./shared/notes/:/usr/src/app/notes
    depends_on:
      admin:
        condition: service_started
    environment:
      - TZ=Europe/Prague
  nginx:
    image: nginx
    ports:
      - 8080:80
      - 9090:90
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      admin:
        condition: service_started
      public:
        condition: service_started