events {

}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://public:8080;
        }
    }

    server {
        listen 90;

        client_max_body_size 100M;

        location / {
            proxy_pass http://admin:9090;
        }
    }
}
